In [38]:
def get_img(img_path,bbox):
    print(bbox)
    temp_file = 'temp.jpg'
    # 处理不同类型的边界框输入
    if isinstance(bbox, str):
        coords = bbox.strip().split()
        x1, y1, x2, y2 = map(float, coords)
    elif isinstance(bbox, (np.ndarray, list, tuple)):
        x1, y1, x2, y2 = map(float, bbox)
    else:
        print(f"错误：不支持的边界框类型 - {type(bbox)}")
        return None
    
    # 打开图像
    img = Image.open(img_path)
    
    # 裁剪图像
    cropped_img = img.crop((x1, y1, x2, y2))
    cropped_img.save(temp_file)
    return temp_file

In [41]:
# 运行本代码，需要在云端下载模型
from PIL import Image
import numpy as np
from XEdu.hub import Workflow as wf # 导入库
animal_list = []
# 指定进行推理的图片路径
img_path = "animal.jpg"

det  = wf(task = 'det_coco') # 实例化模型
cls = wf(task = 'cls_imagenet') # 实例化模型
bboxs,new_img = det.inference(data = img_path,img_type = 'pil') # 进行目标检测推理
print(bboxs)
det.save(new_img,'new_animal.jpg')
for i in bboxs:
    # 使用get_img获得相应区域的图像数据
    temp = get_img(img_path,i)
    cls.inference(data = temp) # 进行分类推理
    # 对推理结果格式化
    result = cls.format_output(lang = "zh")
    animal_list.append(result["预测类别"])
print(animal_list)


det_coco任务模型加载成功！
cls_imagenet任务模型加载成功！
[[340.54025582  38.06538241 713.61453193 499.85350881]
 [102.03352996 177.07339355 304.37288965 393.39610509]]
[340.54025582  38.06538241 713.61453193 499.85350881]
{'预测值': 166, '分数': 0.45671114, '预测类别': 'Walker hound, Walker foxhound'}
[102.03352996 177.07339355 304.37288965 393.39610509]
{'预测值': 285, '分数': 0.51846504, '预测类别': 'Egyptian cat'}
['Walker hound, Walker foxhound', 'Egyptian cat']
